# Generated by Django 4.0.3 on 2022-04-04 19:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(max_length=200)),
                ('Hospital_Code', models.PositiveIntegerField()),
                ('Location', django_countries.fields.CountryField(max_length=2)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Hospital_Name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Id', models.PositiveBigIntegerField()),
                ('Doctor_Name', models.CharField(max_length=45)),
                ('Profile_Picture', models.ImageField(blank=True, upload_to='profile/')),
                ('Date_of_Joining', models.DateField()),
                ('Qualification', models.CharField(max_length=200)),
                ('Specialization', models.CharField(blank=True, max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Doctor_Name', unique=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.hospital')),
            ],
        ),
    ]
